spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/movieclub
    username: root
    password: 11mysql11
  liquibase:
    contexts: prod
  web:
    resources:
      static-locations: classpath:/static/,file:/Users/Dell/uploads/
app:
  storage:
    location: /Users/Dell/uploads/